version: "3"

services:
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sns:4575,sqs:4576,s3
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/var/lib/localstack"